---
title: "Animal Crossing - Critterpedia Project"
author: "Parri Salak"
format: gfm
---

## Background
Animal Crossing New Horizons (ACNH) is a popular video game, and one of my personal favorites. One task that players complete during the game is catching "critters" in order to complete their muesuem's collection and sell them for bells (the in-game currency). In the game, each user has a "Critterpedia" that keeps track of everything they have caught and donated to the muesuem. It is broken down into three categories: Insects, Fish, and Sea Creatures. 

Currently, the data for the these categories of critters is kept seperately. In this project I want to create one complete critterpedia dataframe. This will help see what I can catch and develop a strategy in order to make the most money in game. 

## The Data
For this project, I have three excel files containing the complete information of all of the insects, fish, and sea creatures that can be caught in ACNH. The orginal source of the data I will use is Nookipedia.com, a community initiative to create a structured collection of Animal Crossing: New Horizons data. More information can be found at: https://nookipedia.com/wiki/Community:ACNH_Spreadsheet. I will begin by loading each dataset. 

The first dataset contains information about insects:

```{python}
import pandas as pd
insects = pd.read_excel("Insects.xlsx")
insects.head()
```

```{python}
insects.info()
```

There are 80 different insects that can be caught in ACNH. 

The next dataset contains information about fish:

```{python}
fish = pd.read_excel("Fish.xlsx")
fish.head()
```

```{python}
fish.info()
```

There are also 80 different fish that can be caught. 

The last dataset contains information about sea creatures:

```{python}
sea_creatures = pd.read_excel("Sea_Creatures.xlsx")
sea_creatures .head()
```

```{python}
sea_creatures.info()
```

There are only 40 sea creatures to be caught in ACNH. 

## Data Visualization
Before working on combining this data to make a complete critterpedia dataframe, I want to explore and visualize each type of critter on its own. One of the variables that I am very interested in is "Sell". This is in each critter dataset, and it describes how much you can sell your caught critters for at the general store in game. 

```{python}
import seaborn as sns
import matplotlib.pyplot as plt
```

For the insects, I am going to make a scatteplot showing the relationship between sell price and the weather the are aviable to be caught in.

```{python}
#Boxplot showing Sell price broken down by Weather for Insects
sns.catplot(data=insects, x='Weather', y='Sell', kind='box')
plt.show()
```

It seems like the best time to catch insects is when it is not raining. 

```{python}
max_sell = insects['Sell'].max()
max_sell_insesect = insects[insects['Sell'] == max_sell]
max_sell_insesect
```

The higgest sell price for insects is 12,000 bells. The three insects with this sell price are the giraffe stag, golden stag, and horned hercules. 

Next, I'll look at the catch difficulty of fish and their sell prices. 

```{python}
#I want to specifiy the order of the categories
custom_order = ['Very Easy', 'Easy', 'Medium', 'Hard', 'Very Hard']

#Boxplot showing Sell price broken down by Catch Difficulty for Fish
sns.catplot(data=fish, x='Catch Difficulty', y='Sell', kind='box', order=custom_order)
plt.show()
```

As expected, the sell price appears to increase as the fish become more difficult to catch. 

```{python}
max_sell = fish['Sell'].max()
max_sell_fish = fish[fish['Sell'] == max_sell]
max_sell_fish
```

The highest sell price for fish is 15,000 bells. There are six different fish that can be caught and sold at this price.  

Finally, I will look at the sell price for sea creatures based on their movement speed. 

```{python}
#I want to specifiy the order of the categories
custom_order = ['Stationary', 'Very slow', 'Slow', 'Medium', 'Fast', 'Very fast']

#Boxplot showing Sell price broken down by Movement Speed for Sea Creatures
sns.catplot(data=sea_creatures, x='Sell', y='Movement Speed', kind='box', order=custom_order)
plt.show()
```

Faster sea creatures, which are more difficult to catch, also seem to have a higher sell price. 

```{python}
max_sell = sea_creatures['Sell'].max()
max_sell_sea_creature = sea_creatures[sea_creatures['Sell'] == max_sell]
max_sell_sea_creature
```

Gigas giant clams are the sea creature with the higgest sell price at 15,000 bells. This is the same price as the higgest sell price for fish, but there were many more fish species at that price. 

## Combining the Data
I want to combine the data for insects, fish, and sea creatures into one complete critterpedia dataset. Before doing so, I want to add a new variable to each that will describe the critter type - insect, fish, or sea creature. 

```{python}
insects['type'] = 'insect'
fish['type'] = 'fish'
sea_creatures['type'] = 'sea creature'
```

 I decided to use concat since each dataset has unique observations, or "critters", that will not have matches in the other data. However, each dataset contains almost identical columns/variables. I am specifying an outer join because I want every column from every dataset. 

```{python}
#Concat Insects, Fish, and Sea Creatures
critterpedia = pd.concat([insects, fish, sea_creatures], ignore_index=True, join='outer')
```

```{python}
#Checking that all columns are included in my critterpedia
critterpedia.columns
```

```{python}
#Counting the number of critters of each type to make sure I am not missing any
sns.countplot(data=critterpedia, x='type')
plt.show()
```

How does Sell price differ across types of critters?

```{python}
#Boxplot showing Sell price broken down by type of critter
sns.catplot(data=critterpedia, x='type', y='Sell', kind='box')
plt.show()
```

Just based on sell price for each type of critter, it seems like the best strategy for making money would be to focus on catching sea creatures. 

## Data Cleaning & Handling Missing Data
To begin, there are several columns containing ID type variables. For the purpose of my project, I think it is only neccessary to keep one. 

```{python}
#Making sure there is a unique value for all 200 critters
critterpedia['Name'].nunique()
```

Since "Name" is able to uniquely identify every critter I will use it as my ID variable. 

```{python}
#Dropping extra identification columns
critterpedia = critterpedia.drop(columns=['#','Icon Filename','Critterpedia Filename','Furniture Filename','Unique Entry ID','Internal ID'])
```

I also want to get rid of the variables related to Happy Home Academy (HHA) because it is not relevant in the catching and selling of critters. It is essentially an HOA in animal crossing that evaluates your home decor choices. Since caught critters can be displayed, the HHA has data related to them. However, I do not care what they think of me and my lifestyle choices!! Since this project is for my own personal benefit, I will be excluding their data.

```{python}
critterpedia = critterpedia.drop(columns=critterpedia.filter(regex=r"HHA ").columns)
critterpedia = critterpedia.drop(columns=['Color 1','Color 2','Lighting Type','Version Added', 'Unlocked?'])
```

Additonally, this dataset contains information about what times the critters can be caught for both the northern and southern hemisphere. This is important because the seasons in animal crossing reflect what is haapening in your real-world location. Since I am in the Northern Hemisphere, I only want to keep the data relevant to me. I will delete each of the catch time columns that start with "SH".

```{python}
#Getting rid of southern hemisphere data
critterpedia = critterpedia.drop(columns=critterpedia.filter(regex=r"SH ").columns)

#No longer need NH to specify location, just want month
critterpedia.columns = critterpedia.columns.str.replace(r"NH ", "", regex=True)

critterpedia.columns
```

The variable "Spawn Rates" respresents the percent chance of that critter being present on your island/avaiable to catch in your game at any given time. However, it is a string datatype right now because some of the values are listed as a range like "5-10". I want to fix this and take the lower number to be more conservative. 

```{python}
#Split the string, take the first value, then make it an integer
critterpedia['Spawn Rates'] = critterpedia['Spawn Rates'].str.split("–").str[0].astype('int')
```

Since columns did not match up perfectly between my datasets, I want to find and deal with missing values in my critterpedia. My goal is to make this as complete of a dataset as possible, so I want to minimize the amount of information that is missing. 

```{python}
#Count of missing values
critterpedia.isnull().sum()
```

## Critter Catching Strategy
Finally, I want to compare how the different critter types compare across variables and use the information to make a strategy for catching and selling critters in ACNH. I am interested in some summary statistics so I will group by data by critter type. I want the mean and standard deviation of Sell, Spawn Rates, and Total Catches to Unlock for each group.

The “Total Catches to Unlock” refers to the total critter of that type you must catch in your lifetime before a particular species can start spawning on your island. 

```{python}
grouped_data = critterpedia.groupby('type',as_index=False).agg(
    sell_mean=('Sell','mean'),
    sell_std=('Sell','std'),
    spawn_mean=('Spawn Rates','mean'),
    spawn_std=('Spawn Rates','std'),
    catch_to_unlock_mean=('Total Catches to Unlock','mean'),
    catch_to_unlock_std=('Total Catches to Unlock','std')
)

grouped_data
```

Another variable I am intereste in is surface. It is a yes or no value describing how easy it is to find the critter. Those that are 'yes' appear in the wild, while the 'no's are not part of normal surface wildlife and may require more effort to locate. 

```{python}
#Countplot showing how many surface y/n are each critter type
sns.countplot(data=critterpedia, x='type', hue='Surface')
plt.show()
```

Based on this is, it seems like I am most likely to encounter insects in the wild, and sea creatures might take the most effort to locate. 

Now I want to look at which critters that spawn most frequently will sell for the higgest price. 

```{python}
#Showing critters with the higgest spawn rates that sell for the most bells
target_critters = critterpedia[['Name', 'type', 'Spawn Rates', 'Sell']].sort_values(by=['Spawn Rates', 'Sell'], ascending=False).head(10)
target_critters
```

The results in a top ten target critters that are insects. However, none of the sell prices are over 500. This is quite small considering that the higgest sell price for insects is 12,000. I want to see what the target critters would be if I decided to prioritze sell before spawn rates.

```{python}
#Showing critters with the higgest sell price the spawn the most
target_critters = critterpedia[['Name', 'type', 'Sell', 'Spawn Rates']].sort_values(by=['Sell', 'Spawn Rates'], ascending=False).head(10)
target_critters
```

Although this gives me the critters that can be sold for the most bells, they all have extremely low spawn rates that would make it difficult to specifically aim to catch them. 

Because of this, I am going to filter the data to only those critters with a high enough spawn rate and sell price. I will do that by only looking at critters that are above the average spawn rate since I can expect to encounter them on my island more frequently. Then I will sort these critters by their sell price. 

```{python}
target_critters = critterpedia[['Name', 'type', 'Sell', 'Spawn Rates']]
target_critters = target_critters[target_critters['Spawn Rates'] >= critterpedia['Spawn Rates'].mean()]

target_critters = target_critters.sort_values(by=['Sell', 'Spawn Rates'], ascending=False).head(10)
target_critters
```